name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      
      - name: Checkout tests
        uses: actions/checkout@v3
        with:
          repository: robinrj6/MADE_Project
          path: project

      - name: List contents of the project directory
        run: ls -la
        working-directory: ./project

      - name: Make tests.sh executable
        run: chmod +x tests.sh
        working-directory: ./project

      - name: Exercise tests
        id: tests
        run: project/tests.sh